# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 23:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is admin')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'verbose_name': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('serial', models.CharField(max_length=15, verbose_name='Номер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('time_needed', models.IntegerField(default=0, verbose_name='Необходимое время')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Старт')),
                ('end', models.DateTimeField(auto_now_add=True, verbose_name='Окончание')),
            ],
            options={
                'verbose_name_plural': 'Заявки',
                'verbose_name': 'Заявка',
            },
        ),
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Методики',
                'verbose_name': 'Методика',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('text', models.TextField(verbose_name='Текст')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.Application', verbose_name='Заявка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name_plural': 'Комментарии',
                'verbose_name': 'Комментарий',
            },
        ),
        migrations.CreateModel(
            name='CompleteStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Статусы завершения',
                'verbose_name': 'Статус завершения',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Оборудование',
                'verbose_name': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Старт')),
                ('end', models.DateTimeField(auto_now_add=True, verbose_name='Окончание')),
            ],
            options={
                'verbose_name_plural': 'События',
                'verbose_name': 'Событие',
            },
        ),
        migrations.CreateModel(
            name='EventsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Словарь событий',
                'verbose_name': 'Словарь событий',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Старт')),
                ('end', models.DateTimeField(auto_now_add=True, verbose_name='Окончание')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='main.Application', verbose_name='Заявка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments_as_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('methods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='main.Approach', verbose_name='Методика')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments_as_operator', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name_plural': 'Завершенные эксперименты',
                'verbose_name': 'Завершенный эксперимент',
            },
        ),
        migrations.CreateModel(
            name='ExperimentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Старт')),
                ('end', models.DateTimeField(auto_now_add=True, verbose_name='Окончание')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_experiments', to='main.Application', verbose_name='Заявка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_experiments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name_plural': 'Планируемые эксперименты',
                'verbose_name': 'Планируемый эксперимент',
            },
        ),
        migrations.CreateModel(
            name='JournalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Статусы планируемого эксперимента',
                'verbose_name': 'Статус планируемого эксперимента',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Организации',
                'verbose_name': 'Организация',
            },
        ),
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Права',
                'verbose_name': 'Право',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('rights', models.ManyToManyField(related_name='roles', to='main.Right', verbose_name='Права')),
            ],
            options={
                'verbose_name_plural': 'Роли',
                'verbose_name': 'Роль',
            },
        ),
        migrations.CreateModel(
            name='StageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Статусы принятия в работу',
                'verbose_name': 'Статус принятия в работу',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('short_description', models.CharField(blank=True, max_length=100, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name_plural': 'Станции',
                'verbose_name': 'Станция',
            },
        ),
        migrations.AddField(
            model_name='experimentplan',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_experiments', to='main.Station', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='experimentplan',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_experiments', to='main.JournalStatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='main.Station', verbose_name='Станция'),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.EventsList', verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='application',
            name='approaches',
            field=models.ManyToManyField(related_name='applications', to='main.Approach', verbose_name='Методика'),
        ),
        migrations.AddField(
            model_name='application',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='application',
            name='complete_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.CompleteStatus', verbose_name='Статус завершения'),
        ),
        migrations.AddField(
            model_name='application',
            name='equipment',
            field=models.ManyToManyField(related_name='applications', to='main.Equipment', verbose_name='Обрудование'),
        ),
        migrations.AddField(
            model_name='application',
            name='organizations',
            field=models.ManyToManyField(related_name='applications', to='main.Organization', verbose_name='Организации'),
        ),
        migrations.AddField(
            model_name='application',
            name='participants',
            field=models.ManyToManyField(related_name='applications_as_participant', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='application',
            name='stage_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.StageStatus', verbose_name='Статус принятия в работу'),
        ),
        migrations.AddField(
            model_name='application',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.Station', verbose_name='Станция'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ManyToManyField(blank=True, related_name='users', to='main.Organization', verbose_name='Организации'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.Role', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='user',
            name='special_rights',
            field=models.ManyToManyField(related_name='users', to='main.Right', verbose_name='Особые права'),
        ),
        migrations.AddField(
            model_name='user',
            name='station',
            field=models.ManyToManyField(blank=True, related_name='users', to='main.Station', verbose_name='Станции'),
        ),
    ]
