# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='right',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
