# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170609_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Количество заявок в году')),
            ],
            options={
                'verbose_name': 'Ежегодный счетчик',
                'verbose_name_plural': 'Ежегодный счетчик',
            },
        ),
        migrations.AlterField(
            model_name='completestatus',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='stagestatus',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
    ]
