# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('main', '0010_auto_20170812_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialGroupPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_permissions', to='auth.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialUserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='special_group_permissions',
            field=models.ManyToManyField(to='main.SpecialGroupPermission'),
        ),
        migrations.AddField(
            model_name='application',
            name='special_user_permissions',
            field=models.ManyToManyField(to='main.SpecialUserPermission'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='special_group_permissions',
            field=models.ManyToManyField(to='main.SpecialGroupPermission'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='special_user_permissions',
            field=models.ManyToManyField(to='main.SpecialUserPermission'),
        ),
    ]
