# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170812_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('view_application', 'Смотреть заявку'), ('view_all_applications', 'Смотреть все заявки')), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='specialgrouppermission',
            options={'verbose_name': 'Особое право группы', 'verbose_name_plural': 'Особые права группы'},
        ),
        migrations.AlterModelOptions(
            name='specialuserpermission',
            options={'verbose_name': 'Особое право пользователя', 'verbose_name_plural': 'Особые права пользователей'},
        ),
        migrations.AlterField(
            model_name='application',
            name='special_group_permissions',
            field=models.ManyToManyField(blank=True, to='main.SpecialGroupPermission', verbose_name='Особые права групп'),
        ),
        migrations.AlterField(
            model_name='application',
            name='special_user_permissions',
            field=models.ManyToManyField(blank=True, to='main.SpecialUserPermission', verbose_name='Особые права пользователей'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='special_group_permissions',
            field=models.ManyToManyField(blank=True, to='main.SpecialGroupPermission', verbose_name='Особые права групп'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='special_user_permissions',
            field=models.ManyToManyField(blank=True, to='main.SpecialUserPermission', verbose_name='Особые права пользователей'),
        ),
        migrations.AlterField(
            model_name='specialgrouppermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_permissions', to='auth.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='specialgrouppermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='Право'),
        ),
        migrations.AlterField(
            model_name='specialuserpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='Право'),
        ),
        migrations.AlterField(
            model_name='specialuserpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
