# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default=131313, help_text='HEX color, as #RRGGBB', max_length=7, verbose_name='Color'),
            preserve_default=False,
        ),
    ]
