# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170821_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'permissions': (('view_station_application', 'Может смотреть заявки станции'), ('edit_station_application', 'Может редактировать заявки станции'), ('approve_station_application', 'Может принимать заявки станции'), ('view_plan_station_experiment', 'Может просматривать запланированный эксперимент на станции'), ('plan_station_experiment', 'Может планировать эксперимент на станции'), ('conduct_station_experiment', 'Может проводить эксперимент на станции'), ('view_station_experiment', 'Может просматривать эксперимент на станции')), 'verbose_name': 'Станция', 'verbose_name_plural': 'Станции'},
        ),
    ]
