# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20170822_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='special_group_permissions',
            field=models.ManyToManyField(blank=True, to='main.SpecialGroupPermission', verbose_name='Особые права групп'),
        ),
        migrations.AddField(
            model_name='event',
            name='special_user_permissions',
            field=models.ManyToManyField(blank=True, to='main.SpecialUserPermission', verbose_name='Особые права пользователей'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
    ]
