# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20170822_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('view_application', 'Может смотреть заявку'), ('view_all_applications', 'Может смотреть все заявки'), ('edit_applications', 'Может редактировать заявки'), ('approve_applications', 'Может принимать заявки на станцию'), ('approve_science_applications', 'Может принимать заявки ученым советом'), ('decline_applications', 'Может отклонять заявки'), ('return_applications', 'Может возвращать заявки'), ('comment_applications', 'Может комментировать заявки')), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'permissions': (('view_station_application', 'Может смотреть заявки станции'), ('edit_station_application', 'Может редактировать заявки станции'), ('return_station_application', 'Может возвращать заявки станции'), ('decline_station_application', 'Может возвращать заявки станции'), ('approve_station_application', 'Может принимать заявки станции'), ('approve_science_station_application', 'Может принимать заявки станции'), ('comment_station_application', 'Может комментировать заявки станции'), ('view_plan_station_experiment', 'Может просматривать запланированный эксперимент на станции'), ('plan_station_experiment', 'Может планировать эксперимент на станции'), ('conduct_station_experiment', 'Может проводить эксперимент на станции'), ('view_station_experiment', 'Может просматривать эксперимент на станции')), 'verbose_name': 'Станция', 'verbose_name_plural': 'Станции'},
        ),
    ]
