# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20170822_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=255, verbose_name='key')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('format', models.CharField(blank=True, max_length=255, verbose_name='format')),
                ('unit', models.CharField(blank=True, max_length=255, verbose_name='unit')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='main.Station', verbose_name='станция')),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
            },
        ),
        migrations.CreateModel(
            name='StationMarkValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='value')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='main.StationMark')),
            ],
            options={
                'verbose_name': 'Значение',
                'verbose_name_plural': 'Значения',
            },
        ),
        migrations.AlterUniqueTogether(
            name='stationmark',
            unique_together=set([('key', 'station')]),
        ),
    ]
