# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20170822_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={'permissions': (('conduct_experiment', 'Может проводить эксперимент'), ('view_experiment', 'Может просматривать эксперимент')), 'verbose_name': 'Завершенный эксперимент', 'verbose_name_plural': 'Завершенные эксперименты'},
        ),
        migrations.AlterModelOptions(
            name='experimentplan',
            options={'permissions': (('view_plan_experiment', 'Может просматривать запланированный эксперимент'), ('plan_experiment', 'Может планировать эксперимент')), 'verbose_name': 'Планируемый эксперимент', 'verbose_name_plural': 'Планируемые эксперименты'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'permissions': (('view_station_application', 'Может смотреть заявки станции'), ('edit_station_application', 'Может редактировать заявки станции'), ('return_station_application', 'Может возвращать заявки станции'), ('decline_station_application', 'Может отклонять заявки станции'), ('approve_station_application', 'Может принимать заявки станции'), ('approve_science_station_application', 'Может принимать ученым советом заявки станции'), ('comment_station_application', 'Может комментировать заявки станции'), ('view_plan_station_experiment', 'Может просматривать запланированный эксперимент на станции'), ('plan_station_experiment', 'Может планировать эксперимент на станции'), ('conduct_station_experiment', 'Может проводить эксперимент на станции'), ('view_station_experiment', 'Может просматривать эксперимент на станции'), ('view_station_stats', 'Может просматривать статистику станции')), 'verbose_name': 'Станция', 'verbose_name_plural': 'Станции'},
        ),
        migrations.RenameField(
            model_name='stationmarkvalue',
            old_name='created',
            new_name='time',
        ),
    ]
