# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20170825_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationmarkvalue',
            options={'ordering': ['time'], 'verbose_name': 'Значение', 'verbose_name_plural': 'Значения'},
        ),
        migrations.AlterField(
            model_name='stationmarkvalue',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
    ]
