# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20170831_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialgrouppermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='specialgrouppermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='specialuserpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='specialuserpermission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='application',
            name='special_group_permissions',
        ),
        migrations.RemoveField(
            model_name='application',
            name='special_user_permissions',
        ),
        migrations.RemoveField(
            model_name='event',
            name='special_group_permissions',
        ),
        migrations.RemoveField(
            model_name='event',
            name='special_user_permissions',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='special_group_permissions',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='special_user_permissions',
        ),
        migrations.RemoveField(
            model_name='experimentplan',
            name='special_group_permissions',
        ),
        migrations.RemoveField(
            model_name='experimentplan',
            name='special_user_permissions',
        ),
        migrations.RemoveField(
            model_name='station',
            name='special_group_permissions',
        ),
        migrations.RemoveField(
            model_name='station',
            name='special_user_permissions',
        ),
        migrations.DeleteModel(
            name='SpecialGroupPermission',
        ),
        migrations.DeleteModel(
            name='SpecialUserPermission',
        ),
    ]
