# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20170831_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagestatus',
            name='color',
            field=models.CharField(choices=[('#33СС00', 'Зеленый'), ('#FF0000', 'Красный'), ('#33FFF0', 'Голубой')], default='#33СС00', max_length=7, verbose_name='Цвет'),
        ),
    ]
