# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20170917_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagestatus',
            name='color',
            field=models.CharField(choices=[('#8AFF8A', 'Зеленый'), ('#FF0000', 'Красный'), ('#FFFFA0', 'Желтый')], default='#8AFF8A', max_length=7, verbose_name='Цвет'),
        ),
    ]
