# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 09:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_written', models.TimeField(default=datetime.datetime.now)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Metodic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serial', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=2000)),
                ('time_needed', models.IntegerField(default=0)),
                ('time_start', models.TimeField(default=datetime.datetime.now)),
                ('time_end', models.TimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=100)),
                ('equipment', models.ManyToManyField(to='Dashboard.Equipment')),
                ('metodic', models.ManyToManyField(to='Dashboard.Metodic')),
                ('organization', models.ManyToManyField(to='Dashboard.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rights', models.ManyToManyField(to='Dashboard.Rights')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ManyToManyField(to='Dashboard.Organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Role')),
                ('special_rights', models.ManyToManyField(to='Dashboard.Rights')),
                ('station', models.ManyToManyField(to='Dashboard.Station')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='participant',
            field=models.ManyToManyField(to='Dashboard.User'),
        ),
        migrations.AddField(
            model_name='request',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Station'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Request'),
        ),
    ]
