# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-04 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlaningExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.AddField(
            model_name='request',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='requests_as_author', to='Dashboard.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='organizations',
            field=models.ManyToManyField(related_name='requests', to='Dashboard.Organization'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_written',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='equipment',
            field=models.ManyToManyField(related_name='requests', to='Dashboard.Equipment'),
        ),
        migrations.AlterField(
            model_name='request',
            name='metodic',
            field=models.ManyToManyField(related_name='requests', to='Dashboard.Metodic'),
        ),
        migrations.AlterField(
            model_name='request',
            name='participant',
            field=models.ManyToManyField(related_name='requests_as_participant', to='Dashboard.User'),
        ),
        migrations.AlterField(
            model_name='request',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='Dashboard.Station'),
        ),
        migrations.AlterField(
            model_name='request',
            name='time_end',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='time_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='planingexperiment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_experiments', to='Dashboard.User'),
        ),
        migrations.AddField(
            model_name='planingexperiment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_experiments', to='Dashboard.Request'),
        ),
        migrations.AddField(
            model_name='planingexperiment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_experiments', to='Dashboard.JournalStatus'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments_as_author', to='Dashboard.User'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='metodic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='Dashboard.Metodic'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments_as_operator', to='Dashboard.User'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='Dashboard.Request'),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.EventsList'),
        ),
        migrations.AddField(
            model_name='request',
            name='complete_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='Dashboard.CompleteStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='stage_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='Dashboard.StageStatus'),
            preserve_default=False,
        ),
    ]
