# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-04 22:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20170605_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_written',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='event',
            name='date_end',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='event',
            name='date_start',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='experiment',
            name='date_end',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='experiment',
            name='date_start',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='planingexperiment',
            name='date_end',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='planingexperiment',
            name='date_start',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='request',
            name='date_end',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='request',
            name='date_start',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Dashboard.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_written',
            field=models.TimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='time_end',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='time_start',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='planingexperiment',
            name='time_end',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='planingexperiment',
            name='time_start',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='time_end',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='time_start',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
