# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-04 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20170605_0110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rights',
            new_name='Right',
        ),
    ]
