# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-04 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20170605_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='short_description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
