# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_experiment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='station',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='experiment', to='Dashboard.Station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planingexperiment',
            name='station',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='planning_experiments', to='Dashboard.Station'),
            preserve_default=False,
        ),
    ]
