# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_auto_20170605_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Dashboard.Request'),
        ),
    ]
